"""Produce conservative safety and quality findings for verified Stack-Edu bytes."""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import math
import os
import re
from collections import Counter
from pathlib import Path
from typing import Any

from sai.data.stack_edu_content import (
    StackEduContentError,
    _read_alignment_rows,
    _sealed_regular,
    validate_content_receipt,
)
from sai.data.stack_v2_alignment import (
    StackV2AlignmentError,
    _publish_pair,
    validate_alignment,
)
from sai.data.token_stream import canonical_sha256, sha256_file

FINDING_ROW_SCHEMA = "sai-stack-edu-content-safety-finding-v1"
RECEIPT_SCHEMA = "sai-stack-edu-content-safety-scan-v1"
_FINDING_KEYS = {
    "schema",
    "ordinal",
    "repo_name",
    "path",
    "blob_id",
    "content_sha256",
    "decision",
    "reject_reasons",
    "review_reasons",
    "signals",
    "policy_sha256",
}
_RECEIPT_KEYS = {
    "schema",
    "status",
    "training_authorized",
    "four_b_training_authorized",
    "content_verification",
    "policy",
    "policy_sha256",
    "summary",
    "findings",
    "limitations",
    "receipt_sha256",
}
_HIGH_CONFIDENCE_SECRET_PATTERNS = {
    "aws_access_key_id": r"\b(?:AKIA|ASIA)[A-Z0-9]{16}\b",
    "basic_auth_url": r"https?://[^/\s:@]{1,64}:[^/\s@]{4,128}@",
    "github_token": (
        r"\b(?:gh[pousr]_[A-Za-z0-9]{36,255}|" r"github_pat_[A-Za-z0-9_]{22,255})\b"
    ),
    "google_api_key": r"\bAIza[0-9A-Za-z_-]{35}\b",
    "private_key_pem": r"-----BEGIN (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----",
    "slack_token": r"\bxox[baprs]-[0-9A-Za-z-]{10,}\b",
    "stripe_live_secret": r"\bsk_live_[0-9A-Za-z]{16,}\b",
}
_EMAIL = re.compile(
    r"(?<![A-Za-z0-9._%+-])[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}(?![A-Za-z0-9.-])"
)
_JWT = re.compile(r"\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b")
_HIGH_ENTROPY = re.compile(r"(?<![A-Za-z0-9])[A-Za-z0-9_+/=-]{32,}(?![A-Za-z0-9])")
_GENERIC_CREDENTIAL = re.compile(
    r"(?i)\b(?:api[_-]?key|access[_-]?token|auth[_-]?token|client[_-]?secret|password|passwd|secret[_-]?key)\b\s*(?::|=)\s*[rubf]*(['\"])([^'\"\r\n]{12,})\1"
)
_PLACEHOLDER = re.compile(
    r"(?i)(?:example|sample|dummy|fake|placeholder|changeme|"
    r"replace[_ -]?me|your[_ -]|<[^>]+>|\$\{|xxxxx|000000)"
)
_GENERATED_MARKERS = (
    "@generated",
    "auto-generated file",
    "automatically generated",
    "code generated by",
    "do not edit this file",
)
_IGNORED_EMAIL_DOMAINS = {
    "example.com",
    "example.net",
    "example.org",
    "localhost",
    "users.noreply.github.com",
}
_LIMITATIONS = [
    "bounded_high_confidence_scanner_is_not_exhaustive_secret_detection",
    "email_entropy_syntax_and_generated_markers_require_contextual_review",
    "malware_behavior_and_dependency_supply_chain_analysis_pending",
    "accepted_by_scanner_means_candidate_only_not_source_admission",
    "global_deduplication_benchmark_decontamination_and_curriculum_review_pending",
    "safety_scan_authorizes_no_training_or_source_retention",
]


class StackEduSafetyError(RuntimeError):
    """The verified content, scan policy, findings, or replay differs."""


def _policy() -> dict[str, Any]:
    return {
        "high_confidence_secret_patterns": dict(
            sorted(_HIGH_CONFIDENCE_SECRET_PATTERNS.items())
        ),
        "generic_credential_assignment_minimum_characters": 12,
        "placeholder_suppression_pattern": _PLACEHOLDER.pattern,
        "email_pattern": _EMAIL.pattern,
        "ignored_email_domains": sorted(_IGNORED_EMAIL_DOMAINS),
        "jwt_pattern": _JWT.pattern,
        "high_entropy_pattern": _HIGH_ENTROPY.pattern,
        "high_entropy_minimum_characters": 32,
        "high_entropy_minimum_bits_per_character_milli": 4_000,
        "generated_markers": list(_GENERATED_MARKERS),
        "maximum_line_characters_before_review": 2_000,
        "maximum_repeated_nonempty_line_ppm_before_review": 500_000,
        "python3_syntax_failure_requires_review": True,
        "nul_or_non_whitespace_control_is_rejected": True,
        "secret_pattern_or_nonplaceholder_credential_assignment_is_rejected": True,
        "clean_decision_remains_candidate_only": True,
    }


def _entropy(value: str) -> int:
    counts = Counter(value)
    total = len(value)
    bits = -sum((count / total) * math.log2(count / total) for count in counts.values())
    return round(bits * 1_000)


def _scan_text(text: str, *, source_path: str) -> dict[str, Any]:
    reject = []
    review = []
    secret_counts = {}
    for name, pattern in sorted(_HIGH_CONFIDENCE_SECRET_PATTERNS.items()):
        count = len(re.findall(pattern, text))
        if count:
            secret_counts[name] = count
            reject.append(f"high_confidence_secret:{name}")
    credential_matches = [
        match.group(2)
        for match in _GENERIC_CREDENTIAL.finditer(text)
        if _PLACEHOLDER.search(match.group(2)) is None
    ]
    if credential_matches:
        reject.append("nonplaceholder_generic_credential_assignment")

    emails = []
    for match in _EMAIL.finditer(text):
        value = match.group(0)
        domain = value.rsplit("@", 1)[-1].casefold()
        if domain not in _IGNORED_EMAIL_DOMAINS:
            emails.append(value)
    if emails:
        review.append("personal_email_candidate")
    jwt_count = len(_JWT.findall(text))
    if jwt_count:
        review.append("jwt_like_token")
    entropy_values = {
        value
        for value in _HIGH_ENTROPY.findall(text)
        if _PLACEHOLDER.search(value) is None and _entropy(value) >= 4_000
    }
    if entropy_values:
        review.append("high_entropy_token_candidate")

    forbidden_controls = sum(
        ord(character) < 32 and character not in {"\n", "\r", "\t"}
        for character in text
    )
    if forbidden_controls:
        reject.append("nul_or_non_whitespace_control_character")
    lines = text.splitlines()
    nonempty = [line.strip() for line in lines if line.strip()]
    max_line = max((len(line) for line in lines), default=0)
    repeated_ppm = (
        0
        if not nonempty
        else ((len(nonempty) - len(set(nonempty))) * 1_000_000) // len(nonempty)
    )
    if max_line > 2_000:
        review.append("extreme_line_length_or_minification")
    if repeated_ppm > 500_000:
        review.append("excessive_repeated_nonempty_lines")
    lowered = text.casefold()
    generated = [marker for marker in _GENERATED_MARKERS if marker in lowered]
    if generated:
        review.append("generated_code_marker")
    syntax_status = "parsed_python3"
    try:
        ast.parse(text, filename=source_path)
    except (SyntaxError, ValueError, TypeError, MemoryError):
        syntax_status = "python3_parse_failed"
        review.append("python3_syntax_or_version_review")
    comment_lines = sum(line.lstrip().startswith("#") for line in lines)
    decision = (
        "rejected_high_confidence_sensitive_or_invalid"
        if reject
        else (
            "manual_review_required" if review else "candidate_clean_by_bounded_scanner"
        )
    )
    return {
        "decision": decision,
        "reject_reasons": sorted(set(reject)),
        "review_reasons": sorted(set(review)),
        "signals": {
            "characters": len(text),
            "lines": len(lines),
            "nonempty_lines": len(nonempty),
            "maximum_line_characters": max_line,
            "repeated_nonempty_line_ppm": repeated_ppm,
            "comment_line_ppm": (
                0 if not lines else (comment_lines * 1_000_000) // len(lines)
            ),
            "forbidden_control_codepoints": forbidden_controls,
            "high_confidence_secret_matches": sum(secret_counts.values()),
            "high_confidence_secret_match_counts": secret_counts,
            "nonplaceholder_generic_credential_assignments": len(credential_matches),
            "personal_email_candidates": len(emails),
            "jwt_like_tokens": jwt_count,
            "high_entropy_token_candidates": len(entropy_values),
            "generated_markers": generated,
            "python_syntax_status": syntax_status,
        },
    }


def _read_index(path: Path) -> list[dict[str, Any]]:
    _sealed_regular(path, "Stack-Edu content index")
    rows = []
    try:
        with path.open("r", encoding="utf-8") as handle:
            for line in handle:
                row = json.loads(line)
                if not isinstance(row, dict):
                    raise StackEduSafetyError("Stack-Edu content index differs")
                rows.append(row)
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise StackEduSafetyError("Stack-Edu content index differs") from error
    return rows


def _scan_payload(
    content_receipt_path: Path, findings_output: Path
) -> tuple[dict[str, Any], bytes]:
    content_file_sha256 = sha256_file(content_receipt_path)
    try:
        content_receipt = validate_content_receipt(content_receipt_path)
    except StackEduContentError as error:
        raise StackEduSafetyError("Stack-Edu content verification differs") from error
    if sha256_file(content_receipt_path) != content_file_sha256:
        raise StackEduSafetyError("Stack-Edu content receipt changed while reading")
    alignment_path = Path(content_receipt["alignment"]["path"])
    try:
        alignment = validate_alignment(alignment_path)
    except StackV2AlignmentError as error:
        raise StackEduSafetyError("Stack-Edu alignment differs") from error
    aligned = _read_alignment_rows(alignment)
    index_path = Path(content_receipt["index"]["path"])
    bundle_path = Path(content_receipt["bundle"]["path"])
    index = _read_index(index_path)
    _sealed_regular(bundle_path, "Stack-Edu content bundle")
    if len(index) != len(aligned) or len(index) != content_receipt["index"]["rows"]:
        raise StackEduSafetyError("Stack-Edu scan population differs")
    policy = _policy()
    policy_sha256 = canonical_sha256(policy)
    findings = []
    decisions: Counter[str] = Counter()
    reject_reasons: Counter[str] = Counter()
    review_reasons: Counter[str] = Counter()
    try:
        with bundle_path.open("rb") as bundle:
            for ordinal, (source, descriptor) in enumerate(
                zip(aligned, index, strict=True)
            ):
                candidate = source["candidate"]
                if (
                    descriptor.get("ordinal") != ordinal
                    or descriptor.get("blob_id") != candidate["blob_id"]
                    or descriptor.get("repo_name") != candidate["repo_name"]
                    or descriptor.get("path") != candidate["path"]
                    or descriptor.get("offset") != bundle.tell()
                    or descriptor.get("length_bytes") != candidate["length_bytes"]
                ):
                    raise StackEduSafetyError("Stack-Edu scan identity differs")
                raw = bundle.read(descriptor["length_bytes"])
                if len(raw) != descriptor["length_bytes"] or hashlib.sha256(
                    raw
                ).hexdigest() != descriptor.get("sha256"):
                    raise StackEduSafetyError("Stack-Edu scan content differs")
                try:
                    text = raw.decode("utf-8")
                except UnicodeDecodeError as error:
                    raise StackEduSafetyError(
                        "Stack-Edu scan content differs"
                    ) from error
                scan = _scan_text(text, source_path=candidate["path"])
                row = {
                    "schema": FINDING_ROW_SCHEMA,
                    "ordinal": ordinal,
                    "repo_name": candidate["repo_name"],
                    "path": candidate["path"],
                    "blob_id": candidate["blob_id"],
                    "content_sha256": descriptor["sha256"],
                    "decision": scan["decision"],
                    "reject_reasons": scan["reject_reasons"],
                    "review_reasons": scan["review_reasons"],
                    "signals": scan["signals"],
                    "policy_sha256": policy_sha256,
                }
                findings.append(row)
                decisions[row["decision"]] += 1
                reject_reasons.update(row["reject_reasons"])
                review_reasons.update(row["review_reasons"])
            if bundle.read(1):
                raise StackEduSafetyError("Stack-Edu scan bundle has trailing bytes")
    except OSError as error:
        raise StackEduSafetyError("Stack-Edu scan content differs") from error
    try:
        repeated = validate_content_receipt(content_receipt_path)
    except StackEduContentError as error:
        raise StackEduSafetyError("Stack-Edu content changed while scanning") from error
    if repeated != content_receipt:
        raise StackEduSafetyError("Stack-Edu content changed while scanning")
    encoded = b"".join(
        json.dumps(row, sort_keys=True, separators=(",", ":")).encode() + b"\n"
        for row in findings
    )
    status = (
        "bounded_scan_complete_no_findings_manual_audit_pending"
        if len(findings) > 0
        and decisions.get("candidate_clean_by_bounded_scanner") == len(findings)
        and len(decisions) == 1
        else "bounded_scan_complete_findings_require_filter_or_review"
    )
    payload: dict[str, Any] = {
        "schema": RECEIPT_SCHEMA,
        "status": status,
        "training_authorized": False,
        "four_b_training_authorized": False,
        "content_verification": {
            "path": str(content_receipt_path.resolve()),
            "file_sha256": content_file_sha256,
            "receipt_sha256": content_receipt["receipt_sha256"],
            "rows": content_receipt["index"]["rows"],
            "bundle_sha256": content_receipt["bundle"]["sha256"],
            "index_sha256": content_receipt["index"]["sha256"],
        },
        "policy": policy,
        "policy_sha256": policy_sha256,
        "summary": {
            "rows": len(findings),
            "decision_counts": dict(sorted(decisions.items())),
            "reject_reason_counts": dict(sorted(reject_reasons.items())),
            "review_reason_counts": dict(sorted(review_reasons.items())),
            "complete_population_scanned": True,
        },
        "findings": {
            "path": str(findings_output.resolve()),
            "rows": len(findings),
            "bytes": len(encoded),
            "sha256": hashlib.sha256(encoded).hexdigest(),
            "ordered_sha256": canonical_sha256(findings),
        },
        "limitations": _LIMITATIONS,
    }
    payload["receipt_sha256"] = canonical_sha256(payload)
    return payload, encoded


def scan_content(
    content_receipt: Path, findings_output: Path, receipt_output: Path
) -> dict[str, Any]:
    """Scan every verified content row and freeze exact findings."""

    payload, encoded = _scan_payload(Path(content_receipt), Path(findings_output))
    receipt_encoded = (json.dumps(payload, sort_keys=True, indent=2) + "\n").encode()
    try:
        _publish_pair(
            Path(findings_output), encoded, Path(receipt_output), receipt_encoded
        )
    except Exception as error:
        raise StackEduSafetyError("Stack-Edu safety output boundary differs") from error
    os.chmod(findings_output, 0o444)
    os.chmod(receipt_output, 0o444)
    return validate_safety_receipt(Path(receipt_output))


def validate_safety_receipt(receipt: Path) -> dict[str, Any]:
    """Reopen and replay the complete bounded safety scan."""

    _sealed_regular(Path(receipt), "Stack-Edu safety receipt")
    try:
        payload = json.loads(Path(receipt).read_bytes())
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise StackEduSafetyError("Stack-Edu safety receipt differs") from error
    unsigned = {key: value for key, value in payload.items() if key != "receipt_sha256"}
    if (
        not isinstance(payload, dict)
        or set(payload) != _RECEIPT_KEYS
        or payload.get("schema") != RECEIPT_SCHEMA
        or payload.get("receipt_sha256") != canonical_sha256(unsigned)
        or payload.get("training_authorized") is not False
        or payload.get("four_b_training_authorized") is not False
        or payload.get("limitations") != _LIMITATIONS
    ):
        raise StackEduSafetyError("Stack-Edu safety receipt differs")
    parent = payload.get("content_verification")
    findings = payload.get("findings")
    if (
        not isinstance(parent, dict)
        or set(parent)
        != {
            "path",
            "file_sha256",
            "receipt_sha256",
            "rows",
            "bundle_sha256",
            "index_sha256",
        }
        or not isinstance(findings, dict)
        or set(findings) != {"path", "rows", "bytes", "sha256", "ordered_sha256"}
    ):
        raise StackEduSafetyError("Stack-Edu safety receipt differs")
    content_path = Path(parent["path"])
    findings_path = Path(findings["path"])
    if sha256_file(content_path) != parent["file_sha256"]:
        raise StackEduSafetyError("Stack-Edu safety parent differs")
    metadata = _sealed_regular(findings_path, "Stack-Edu safety findings")
    expected, encoded = _scan_payload(content_path, findings_path)
    if (
        expected != payload
        or metadata.st_size != len(encoded)
        or findings_path.read_bytes() != encoded
    ):
        raise StackEduSafetyError("Stack-Edu safety replay differs")
    return payload


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    scan = commands.add_parser("scan")
    scan.add_argument("--content-receipt", type=Path, required=True)
    scan.add_argument("--findings-output", type=Path, required=True)
    scan.add_argument("--receipt-output", type=Path, required=True)
    validate = commands.add_parser("validate")
    validate.add_argument("--receipt", type=Path, required=True)
    args = parser.parse_args()
    if args.command == "scan":
        payload = scan_content(
            args.content_receipt, args.findings_output, args.receipt_output
        )
    else:
        payload = validate_safety_receipt(args.receipt)
    print(
        json.dumps(
            {"status": payload["status"], "receipt_sha256": payload["receipt_sha256"]},
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
